### ISSUE TITLE
Migrate ⍺ to ∂

### ISSUE THREAD

**Issue by jjg-123** [ncsa/qdl#61]
Using ⍺ (\u237A) as a symbol for the applies operator (in addition to apply()) means font options in the GUI are limited to pretty much ugly built in Java options. ∂ (\u2202) is more available, since Unicode fonts generally seem to cut off starting at the 2300 code point (additional Math symbols). Anything in the 2200 range is a standard math symbol so most Math-y fonts have them.

Moral of the story is that just because there is a standard does not mean anyone gives a hoot and follows it.

**Comment by jbasney** [comment]
Will this change cause a problem for existing qdl policies that use the ⍺ (\u237A) symbol?
